# Generated by Django 4.2.5 on 2023-10-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_remove_capturedimage_prediction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('classification', models.CharField(max_length=1)),
            ],
        ),
    ]
